# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Code coverage

on:
  pull_request:
    branches: [ master ]

jobs: 
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15]

    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.20.3
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm install
    - uses: artiomtr/jest-coverage-report-action@v2
      with:
        package-manager: pnpm
        test-script: pnpm test:cov
        github-token: ${{ secrets.GITHUB_TOKEN }}